name: Build, Test and Publish

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # set for bringing the tag inforation for all teh branches
        # use it with caution when git is large
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Tag the release version
        run: |
          git tag some-tag
      - name: Install python dependencies
        run: |
          /bin/bash -x run.sh install
      - name: Lint, format, and other static code quality check
        run: |
          /bin/bash -x run.sh lint:ci
      - name: Build python package
        run: |
          /bin/bash -x run.sh build

      - name: publish to Test Pypi
        #  if this a push event
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        run: |
          /bin/bash -x run.sh publish:test
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN}}
      - name: publish to Prod Pypi
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        run: |
          /bin/bash -x run.sh publish:PROD
        env:
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN}}
      - name: Push Tags
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        run: |
          git push origin --tags
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pre-commit
      # - name: pre-commit configuration picks config from pyproject.toml
      #   run: |
      #     SKIP=no-commit-to-branch pre-commit run --all-file

  # https://docs.github.com/en/actions/learn-github-actions/contexts

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        # added two new contexts for secrets and vars
      - name: Dump secrets
        env:
          secrets: ${{ toJson(secrets) }}
        run: echo "$secrets"
      - name: Dump variables
        env:
          vars: ${{ toJson(vars) }}
        run: echo "$vars"
